import { Story, Meta } from '@storybook/react';
import SearchList, { Props } from '.';

export default {
  title: 'TMDB Search/Organisms/SearchList',
  component: SearchList,
} as Meta;

const Template: Story<Props> = (args) => <SearchList {...args} />;

export const Default = Template.bind({});
Default.args = {
  results: [
    {
      adult: false,
      backdrop_path: '/nVKRspU9SQEs2gNrms8cDKsI4vx.jpg',
      genre_ids: [28, 878, 12, 10752],
      id: 588228,
      original_language: 'en',
      original_title: 'The Tomorrow War',
      overview: '',
      poster_path: '/xipF6XqfSYV8DxLqfLN6aWlwuRp.jpg',
      release_date: '2021-06-30',
      title: 'トゥモロー･ウォー',
      video: false,
      vote_average: 8.7,
      vote_count: 695,
      popularity: 771.266,
    },
    {
      adult: false,
      backdrop_path: '/tyZmdMdI3jLs93HDObOZkdq4J7z.jpg',
      genre_ids: [27, 9648, 10749],
      id: 591273,
      original_language: 'en',
      original_title: 'Fear Street Part One: 1994',
      overview: '',
      poster_path: '/pxHo4FWIhwv2rETUPo0gvSceYJB.jpg',
      release_date: '2021-07-02',
      title: 'フィアー・ストリート Part 1: 1994',
      video: false,
      vote_average: 7.1,
      vote_count: 90,
      popularity: 101.794,
    },
    {
      adult: false,
      backdrop_path: '/z2UtGA1WggESspi6KOXeo66lvLx.jpg',
      genre_ids: [878, 53, 27],
      id: 520763,
      original_language: 'en',
      original_title: 'A Quiet Place Part II',
      overview: '',
      poster_path: '/6wUN67cWo6mLlhsrSVxZY0pmlSq.jpg',
      release_date: '2021-05-21',
      title: 'A Quiet Place Part II',
      video: false,
      vote_average: 7.8,
      vote_count: 1230,
      popularity: 3051.945,
    },
    {
      adult: false,
      backdrop_path: '/uSWyMhLCKGCXgOk9dDEXHMtkT3U.jpg',
      genre_ids: [16, 35, 12, 10751],
      original_language: 'en',
      original_title: 'The Boss Baby: Family Business',
      poster_path: '/5dExO5G2iaaTxYnLIFKLWofDzyI.jpg',
      video: false,
      vote_average: 7.6,
      title: 'ボス・ベイビー ファミリー・ミッション',
      overview: '',
      release_date: '2021-07-01',
      vote_count: 109,
      id: 459151,
      popularity: 467.415,
    },
    {
      adult: false,
      backdrop_path: '/ok7RdHhVngnwkvKj09tvtOvypG.jpg',
      genre_ids: [80, 18, 53, 9648],
      id: 649409,
      original_language: 'en',
      original_title: 'No Sudden Move',
      overview: '',
      poster_path: '/34BmdJkdvRweC3xJJFlOFQ2IbYc.jpg',
      release_date: '2021-06-24',
      title: 'No Sudden Move',
      video: false,
      vote_average: 7.1,
      vote_count: 29,
      popularity: 37.663,
    },
    {
      adult: false,
      backdrop_path: '/5HjzYTihkH7EvOWSE7KcsF6pBMM.jpg',
      genre_ids: [10751, 35, 12, 16, 14],
      id: 522478,
      original_language: 'en',
      original_title: 'Peter Rabbit 2: The Runaway',
      overview: '',
      poster_path: '/hP0IRnHhNuMfOhwxJD28wI3JyX7.jpg',
      release_date: '2021-03-25',
      title: 'ピーターラビット2 バーナバスの誘惑',
      video: false,
      vote_average: 7.4,
      vote_count: 90,
      popularity: 236.38,
    },
    {
      adult: false,
      backdrop_path: '/6jEiWUxDsRS6o7ayhLbaJKVVAjq.jpg',
      genre_ids: [27, 53],
      id: 672741,
      original_language: 'en',
      original_title: 'Till Death',
      overview: '',
      poster_path: '/sTPGfWghOGL7HnUhV5QFFWBaHbV.jpg',
      release_date: '2021-07-01',
      title: 'Till Death',
      video: false,
      vote_average: 7,
      vote_count: 11,
      popularity: 77.312,
    },
    {
      adult: false,
      backdrop_path: '/cwYMez1g8Lfsz9eF8EDyedBwpa.jpg',
      genre_ids: [9648, 53],
      id: 604360,
      original_language: 'ko',
      original_title: '제8일의 밤',
      overview: '',
      poster_path: '/a11TdGOWqASvbeMs7q0a1YLa5K.jpg',
      release_date: '2021-07-02',
      title: '제8일의 밤',
      video: false,
      vote_average: 6.4,
      vote_count: 5,
      popularity: 59.907,
    },
    {
      video: false,
      vote_average: 7.2,
      overview: '',
      release_date: '2021-06-14',
      vote_count: 93,
      adult: false,
      backdrop_path: '/gJckSA3Evn5gouT62rytjLbTzoj.jpg',
      title: "Hitman's Wife's Bodyguard",
      genre_ids: [28, 35, 53],
      id: 522931,
      original_language: 'en',
      original_title: "Hitman's Wife's Bodyguard",
      poster_path: '/oht9CZHNDBEu5KitgxUsb0LhQ8v.jpg',
      popularity: 296.685,
    },
    {
      original_title: 'America: The Motion Picture',
      poster_path: '/j0HnLa6FtGcslbqClKOIyvCXfpe.jpg',
      video: false,
      vote_average: 5.2,
      overview: '',
      release_date: '2021-06-30',
      vote_count: 26,
      adult: false,
      backdrop_path: '/kkXMDMRGtuO9cewtFjWNREC74nf.jpg',
      title: 'America: The Motion Picture',
      genre_ids: [28, 35, 36, 16, 14],
      id: 739542,
      original_language: 'en',
      popularity: 137.417,
    },
    {
      adult: false,
      backdrop_path: '/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg',
      genre_ids: [16, 35, 10751, 14],
      id: 508943,
      original_language: 'en',
      original_title: 'Luca',
      overview:
        '水にぬれると変身し、自由自在に海を泳ぐことができる不思議な能力を持つ種族シー・モンスターの少年ルカ。彼は人間と交わってはいけないというおきてを破り、北イタリアにある海辺の町ポルト・ロッソを訪れる。シー・モンスターを目にしたことがなく、恐れを抱く人間たちに正体を知られないようにしながら、ルカは海では体験できなかった人間の世界の風景に感激する。',
      poster_path: '/2tITlt8lx5sTs6ZAKWqiOwWTT3t.jpg',
      release_date: '2021-06-17',
      title: 'あの夏のルカ',
      video: false,
      vote_average: 8.2,
      vote_count: 1906,
      popularity: 5609.753,
    },
    {
      adult: false,
      backdrop_path: '/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg',
      title: 'F9',
      genre_ids: [28, 12, 80],
      original_language: 'en',
      original_title: 'F9',
      poster_path: '/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg',
      video: false,
      vote_average: 7.7,
      vote_count: 370,
      overview: '',
      release_date: '2021-05-19',
      id: 385128,
      popularity: 3231.578,
    },
    {
      adult: false,
      backdrop_path: '/5MlvT4DZIdkpb7A9t375HVoiJ1v.jpg',
      genre_ids: [28, 53],
      id: 646207,
      original_language: 'en',
      original_title: 'The Ice Road',
      overview: '',
      poster_path: '/pj6UQPrtmC0snzPeU1HUhGWTgz6.jpg',
      release_date: '2021-06-24',
      title: 'The Ice Road',
      video: false,
      vote_average: 7.5,
      vote_count: 215,
      popularity: 206.536,
    },
    {
      adult: false,
      backdrop_path: '/8xt0ILZbqPsR8BVOIoY13ck6XtL.jpg',
      genre_ids: [27, 35, 9648],
      id: 800497,
      original_language: 'en',
      original_title: 'Werewolves Within',
      overview: '',
      poster_path: '/WoG2tvwanOMlU0qsbxpf9Qd3y.jpg',
      release_date: '2021-06-25',
      title: 'Werewolves Within',
      video: false,
      vote_average: 7.4,
      vote_count: 14,
      popularity: 25.334,
    },
    {
      adult: false,
      backdrop_path: '/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg',
      title: 'モータルコンバット',
      genre_ids: [28, 14, 12],
      original_language: 'en',
      original_title: 'Mortal Kombat',
      poster_path: '/92j6FAX5gEJUMvGdTycpvn05EA7.jpg',
      video: false,
      vote_average: 7.5,
      vote_count: 3183,
      overview: '',
      release_date: '2021-04-07',
      id: 460465,
      popularity: 1374.407,
    },
    {
      title: 'The God Committee',
      vote_average: 9,
      overview: '',
      release_date: '2021-07-02',
      id: 653024,
      adult: false,
      backdrop_path: '/w8mEsc2IKiqt8fxcdPlZR9nxZlF.jpg',
      genre_ids: [53, 18],
      vote_count: 2,
      original_language: 'en',
      original_title: 'The God Committee',
      poster_path: '/p1dXPdz5C1tPpPIy3kth3rTCOQe.jpg',
      video: false,
      popularity: 52.224,
    },
    {
      adult: false,
      backdrop_path: '/ohBudODLg90h2R8jQf4DvfGjY4A.jpg',
      genre_ids: [9648, 80, 53, 10749],
      id: 695969,
      original_language: 'hi',
      original_title: 'हसीन दिलरुबा',
      overview: '',
      poster_path: '/6YrHAIMp0NLMUv5pECH660de1Bm.jpg',
      release_date: '2021-07-02',
      title: 'हसीन दिलरुबा',
      video: false,
      vote_average: 6.5,
      vote_count: 2,
      popularity: 49.837,
    },
    {
      adult: false,
      backdrop_path: '/6azpBJGcLx9SKif8h9VMnflBfa.jpg',
      title: 'ブラック・ウィドウ',
      genre_ids: [28, 12, 53],
      original_language: 'en',
      original_title: 'Black Widow',
      poster_path: '/61F1sWO08wwD9i1wVH1IqEo21rg.jpg',
      video: false,
      vote_average: 8.1,
      vote_count: 8,
      overview: '',
      release_date: '2021-07-07',
      id: 497698,
      popularity: 444.799,
    },
    {
      video: false,
      vote_average: 8,
      overview: '',
      release_date: '2021-05-25',
      title: '死霊館 悪魔のせいなら、無罪。',
      adult: false,
      backdrop_path: '/qi6Edc1OPcyENecGtz8TF0DUr9e.jpg',
      genre_ids: [27, 9648, 53],
      vote_count: 2798,
      original_language: 'en',
      original_title: 'The Conjuring: The Devil Made Me Do It',
      poster_path: '/xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg',
      id: 423108,
      popularity: 1830.777,
    },
    {
      adult: false,
      backdrop_path: '/z8TvnEVRenMSTemxYZwLGqFofgF.jpg',
      genre_ids: [28, 14, 12],
      id: 458576,
      original_language: 'en',
      original_title: 'Monster Hunter',
      overview:
        '作戦行動中に砂漠で消息を絶った偵察小隊。その探索に当たっていたアルテミス（ミラ・ジョヴォヴィッチ）率いる特殊部隊は、突然、激しい砂嵐に飲み込まれてしまう。砂嵐が去った後、彼らの眼前に現れたのは、未知なる世界の光景と…ありえないサイズの超巨大モンスター!! 近代兵器が通用しないモンスターの猛攻に、小隊は全滅寸前にまで追い込まれる。絶体絶命の危機を救ったのは、見慣れぬ装備を身にまとい、巨大な剣を携えた一人の男（トニー・ジャー）。彼はモンスターを狩るために戦う者＝モンスターハンターであった。\r アルテミス達はなぜ、モンスターが跋扈する世界にやって来たのか? 元の世界に戻る方法はあるのか? すべての真実を知るためには、次々襲来する巨大モンスター達を倒し、生き残るしかない。狩るのは人間か? モンスターか!? 究極のサバイバルがいま始まる!',
      poster_path: '/cDlN1OAmTeiho1Vpg3ip5j2Kxrk.jpg',
      release_date: '2020-12-03',
      title: 'モンスターハンター',
      video: false,
      vote_average: 7,
      vote_count: 1813,
      popularity: 629.935,
    },
  ],
};
